### PR TITLE
Update open-monitoring.md

### PR DESCRIPTION
**Pull request by jeromeinsf**
Fixing capitalization on Amazon managed Service for Prometheus

*Issue #, if available:* N/A

*Description of changes:* Fixing capitalization on Amazon managed Service for Prometheus

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jeromeinsf** [comment]
@mohitpali @ellkend-aws could you take a look?

**Review by mohitpali — APPROVED** [review]
LGTM

**Comment by jeromeinsf** [comment]
@mohitpali what's the next step to get it merged?

**Review by mohitpali — APPROVED** [review]

**Comment by mohitpali** [comment]
@ellkend-aws Could you please review and merge please ?

**Review by cmyoshid — APPROVED** [review]
Thanks for submitting the MSK Developer Guide github edit. Approving and publishing.

**Pull request merged**
